from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    MyTokenObtainPairView, 
    Follow, 
    AllProfiles,
    all_sellers_profile,
    # Just_sellers,
    UserProfileDetails,
    prof_pics_update,
    Critical,
    Positive,
    Unfollow,
    UserProfileDelete,
    BlockUser,
    BlockSeller,
    UnblockSeller,
    UnblockUser,
    RequestPasswordResetEmail,
    PasswordTokenCheckAPI,
    SetNewPasswordAPIView,
    # passwordChange,
    CreateReview,
    # AllReviews,
    PostNotifications,
    PostProductNotifications,
    ProductGetNotifications,
    ProductEditNotification,
    GetNotifications,
    EditNotification,
    SellersProfileForm,
    AllFollowers,
    AllFollowing,
    MonthlyUsers,
    AllUsers,
    YourOrders,
    TotalUsers,
    UserRegistrationView,
    )
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

urlpatterns = [
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),   
    path('register/', UserRegistrationView.as_view(), name='user-registration'),
    path('allprofiles/', AllProfiles.as_view(), name='all_products'),   
    path('profdetails/<str:username>/', UserProfileDetails.as_view(), name='profile_details'),   
    path('delete/<int:pk>/', UserProfileDelete.as_view(), name='delete'),   
    path('blockuser/<int:pk>/', BlockUser.as_view(), name='blockuser'),   
    path('blockseller/<int:pk>/', BlockSeller.as_view(), name='blockseller'),   
    path('unblockseller/<int:pk>/', UnblockSeller.as_view(), name='unblockseller'),   
    path('unblockuser/<int:pk>/', UnblockUser.as_view(), name='unblockuser'),   
    path('reset_password/', RequestPasswordResetEmail.as_view(),name="reset_password"),
    path('password-reset/<uidb64>/<token>/', PasswordTokenCheckAPI.as_view(), name='password-reset-confirm'),
    # path('password-change/', passwordChange,name="password-change"),
    path('password-reset-complete/', SetNewPasswordAPIView.as_view(), name='password-reset-complete'),
    # path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),   
    # path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),   
    # path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),   
    # path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),   
    path('sellersprofileform/<int:pk>/', SellersProfileForm.as_view(), name='sellersprofileform'),   
    path('follow/<str:username>/', Follow.as_view(), name='Follow'),   
    path('unfollow/<str:username>/', Unfollow.as_view(), name='Follow'),   
    path('allfollowers/<str:username>/', AllFollowers.as_view(), name='allfollowers'),   
    path('allfollowing/<str:username>/', AllFollowing.as_view(), name='allfollowing'),   
    # pat('isFollowersdetails/<int:pk>/', isFollowersDetails.as_view(), name='FollowersDetails'),   
    path('sellers/', all_sellers_profile.as_view(), name='sellers'),   
    # path('just-sellers/<int:pk>/', Just_sellers.as_view(), name='just-sellers'),   
    path('update/profilepics/<int:pk>/', prof_pics_update.as_view(), name='update_prof_pics'),   
    path('criticalrating/<str:username>/', Critical.as_view(), name='criticalrating'),   
    path('positiverating/<str:username>/', Positive.as_view(), name='positiverating'),   
    path('createreview/', CreateReview.as_view(), name='createreview'),   
    # path('allreviews/<int:pk>/', AllReviews.as_view(), name='allreviews'),   
    path('postnotifications/', PostNotifications.as_view(), name='postnotifications'),   
    path('getnotifications/', GetNotifications.as_view(), name='getnotifications'),   
    path('editnotifications/<int:pk>/', EditNotification.as_view(), name='editnotifications'),   
    path('postproductnotifications/', PostProductNotifications.as_view(), name='postproductnotifications'),   
    path('getproductnotifications/', ProductGetNotifications.as_view(), name='getproductnotifications'),   
    path('productedit/<int:pk>/', ProductEditNotification.as_view(), name='productedit'),   
    # path('checkflutterwave/<int:pk>/', checkFlutterWave.as_view(), name='getnotifications'),   
    path('monthlyusers/', MonthlyUsers.as_view(), name='monthlyusers'),   
    path('totalusers/', TotalUsers.as_view(), name='totalusers'),   
    path('allusers/', AllUsers.as_view(), name='allusers'),   
    path('yourorders/<str:username>/', YourOrders.as_view(), name='ordersusersmade'),   
    # path('request-reset-email/', RequestPasswordResetEmail.as_view(),
    #      name="request-reset-emai"
]