# Generated by Django 4.1.6 on 2023-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnotifications',
            name='seen',
            field=models.CharField(choices=[('seen', 'seen'), ('unseen', 'unseen')], default='unseen', max_length=100),
            preserve_default=False,
        ),
    ]
