# Generated by Django 4.2.1 on 2023-05-31 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isFollowing',
        ),
    ]
