# Generated by Django 4.2.1 on 2023-12-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_remove_profile_isfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
