# Generated by Django 4.1.6 on 2023-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_productnotifications_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.ManyToManyField(default=3, related_name='productnotification', to='profileapp.productnotifications'),
        ),
    ]
