# Generated by Django 4.2.1 on 2024-01-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
