# Generated by Django 4.2.1 on 2024-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
