# Generated by Django 4.1.6 on 2023-03-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
