# Generated by Django 4.1.6 on 2023-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_remove_profile_delivery_delete_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='item',
            field=models.TextField(blank=True, null=True),
        ),
    ]
