# Generated by Django 4.2.1 on 2024-01-19 04:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_alter_profile_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pics',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='pics',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
