# Generated by Django 4.1.6 on 2023-03-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_profile_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.TextField(choices=[('true', 'true'), ('false', 'false')], default='false'),
        ),
    ]
