# Generated by Django 4.2.1 on 2024-01-20 21:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_alter_profile_pics_alter_review_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pics',
            field=cloudinary.models.CloudinaryField(blank=True, default='c40te5wgb08lfd5em1pq', max_length=255, null=True, verbose_name='image'),
        ),
    ]
