# Generated by Django 4.1.6 on 2023-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_profile_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='flutterWaveId',
            new_name='subaccount_percentage',
        ),
        migrations.AddField(
            model_name='profile',
            name='subaccountId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
