# Generated by Django 4.2.1 on 2023-05-27 04:06

from django.db import migrations, models
import django.db.models.deletion
import productapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostBoughtData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics', models.IntegerField(default=0)),
                ('computing', models.IntegerField(default=0)),
                ('homeandoffice', models.IntegerField(default=0)),
                ('phonesandcomputers', models.IntegerField(default=0)),
                ('womens_fashion', models.IntegerField(default=0)),
                ('mens_fashion', models.IntegerField(default=0)),
                ('baby_product', models.IntegerField(default=0)),
                ('game', models.IntegerField(default=0)),
                ('sports_wears', models.IntegerField(default=0)),
                ('automobiles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('computing', 'computing'), ('home & office', 'home & office'), ('baby product', 'baby product'), ('game', 'game'), ('fashion', 'fashion')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, default='/posts/default.png', null=True, upload_to=productapp.models.upload_to)),
                ('price', models.FloatField()),
                ('size', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=70, null=True)),
                ('sellerName', models.CharField(default='kosi', max_length=70)),
                ('sellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='profileapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20)),
                ('item_qty', models.TextField()),
                ('cartSize', models.TextField(default=0)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('item', models.ManyToManyField(related_name='orders', to='productapp.product')),
                ('owners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile')),
            ],
        ),
    ]
