# Generated by Django 4.1.6 on 2023-02-24 04:53

from django.db import migrations, models
import django.db.models.deletion
import productapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('buyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_buyers', to='profileapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Your_rder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_orders', to='productapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('computing', 'computing'), ('home & office', 'home & office'), ('phones & computers', 'phones & computers'), ("women's fashion", "women's fashion"), ("men's fashion", "men's fashion"), ('baby product', 'baby product'), ('game', 'game'), ('sports wears', 'sports wears'), ('automobiles', 'automobiles')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, default='/posts/default.png', null=True, upload_to=productapp.models.upload_to)),
                ('price', models.FloatField()),
                ('size', models.IntegerField(blank=True, null=True)),
                ('sellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='profileapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('computing', 'computing'), ('home & office', 'home & office'), ('phones & computers', 'phones & computers'), ("women's fashion", "women's fashion"), ("men's fashion", "men's fashion"), ('baby product', 'baby product'), ('game', 'game'), ('sports wears', 'sports wears'), ('automobiles', 'automobiles')], max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, default='/posts/default.png', null=True, upload_to=productapp.models.upload_to)),
                ('price', models.FloatField()),
                ('size', models.IntegerField(blank=True, null=True)),
                ('sellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_product_sellers', to='profileapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='productapp.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='sellers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sellers', to='profileapp.profile'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ManyToManyField(to='productapp.product')),
            ],
        ),
    ]
