# Generated by Django 4.1.6 on 2023-03-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
