# Generated by Django 4.2.1 on 2024-01-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
