# Generated by Django 4.2.1 on 2024-01-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_cart_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
