# Generated by Django 4.1.6 on 2023-03-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_notification'),
        ('productapp', '0003_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='owners',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PendingProduct',
        ),
    ]
