# Generated by Django 4.2.1 on 2024-01-19 04:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_alter_cart_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='/posts/default.png', max_length=255, null=True),
        ),
    ]
