# Generated by Django 4.1.6 on 2023-03-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_remove_cart_item_cart_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
