# Generated by Django 4.1.6 on 2023-03-31 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_profile_blocked'),
        ('productapp', '0006_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='productapp.product')),
                ('owners', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='your_rder',
            name='your_orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Your_rder',
        ),
    ]
