# Generated by Django 4.1.6 on 2023-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_remove_cart_item_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellerName',
            field=models.CharField(default='kosi', max_length=70),
        ),
    ]
