# Generated by Django 4.1.6 on 2023-04-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0009_product_sellername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='productapp.product'),
        ),
    ]
