# Generated by Django 4.1.6 on 2023-04-04 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_profile_blocked'),
        ('productapp', '0010_alter_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completed',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='owners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile'),
        ),
    ]
