# Generated by Django 4.1.6 on 2023-04-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0011_cart_completed_alter_cart_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='completed',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20),
        ),
    ]
