# Generated by Django 4.1.6 on 2023-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0012_alter_cart_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(related_name='orders', to='productapp.product'),
        ),
    ]
