# Generated by Django 4.1.6 on 2023-04-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0013_alter_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_qty',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='1', max_length=20),
        ),
    ]
