# Generated by Django 4.1.6 on 2023-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0014_cart_item_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_qty',
            field=models.TextField(),
        ),
    ]
