# Generated by Django 4.1.6 on 2023-04-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0018_dicty_keyval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
