# Generated by Django 4.1.6 on 2023-04-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0019_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostBoughtData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_bought', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='keyval',
            name='container',
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
