# Generated by Django 4.1.6 on 2023-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0020_mostboughtdata_delete_data_remove_keyval_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostboughtdata',
            name='most_bought',
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='automobiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='baby_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='computing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='electronics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='homeandoffice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='mens_fashion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='phonesandcomputers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='sports_wears',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mostboughtdata',
            name='womens_fashion',
            field=models.IntegerField(default=0),
        ),
    ]
